# Generated by Django 5.1.7 on 2025-04-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HM',
            new_name='Admin',
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
    ]
