# Generated by Django 5.1.7 on 2025-04-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
